### PR TITLE
Tags inline again

### PR DESCRIPTION
**Pull request by SubJunk**
This re-adds tag functionality to the image bulk edit pages, and removes the list of unused tags from the boxes, since that was the reason for the client-side performance issues.

I also suggest that in addition to this, tag_suggest is enabled by default, since that will mean that no functionality is lost at all

### CODE REVIEW

**Comment by acrylian** [comment]
I am not sure about this. I do have tags on the edit page and tag_suggest is actually already on by default on the backend.

Be sure your fork is up to date as GitHub lists this as January 26th.

**Comment by SubJunk** [comment]
The functionality before this is that the album edit page displays an un-editable list of tags, and you can then go to the single image page to add/edit tags, unless I'm missing something.
This restores the old functionality by reverting e50e486, d77ff0d and 3ef821e (and partially reverting 885f098 as a consequence)

**Comment by acrylian** [comment]
No, the album edit page should show a list of tags as on the images as you can assign tags to an album directly as well. All is as it is meant to be actually.

**Comment by SubJunk** [comment]
@acrylian I meant the image bulk edit pages, I mistakenly referred to them as the album edit page

**Comment by acrylian** [comment]
Sorry, we won't add the tags back on the image bulk edit pages. I think the reason still applies as you can have lots of tags assigned already. But more importantly I think having a "crippled" list with just the already assigned tags is confusing UI wise for especially new users (if I understood it correctly).  Better to have it in one place only as we otherwise will have to explained it lots of times why there is a difference.

**Comment by SubJunk** [comment]
@acrylian the way I see it, when tag_suggest is enabled, having the unused tags displayed in each box is redundant and superfluous, especially in situations where there are lots of tags.
Scrolling through the list of thousands of unused tags to try to find a particular one is very time-consuming, so that functionality is of limited use, whereas tag suggest offers the same ability (to add tags without typing the whole thing, and to be sure you are adding the exact tag that exists instead of a slightly different one) but in a more convenient way.

The screenshot you attached shows an uneditable list of tags, which doesn't seem useful - this PR allows us to add and edit tags from that screen.

**Comment by acrylian** [comment]
No problem, just trying to understand what you exactly meant which I think I now do finally. We will discuss that.

**Comment by fretzl** [comment]
Suppose you do have thousands of tags. Then *tag_suggest* is not going to be easier because you don't know what letters to begin with, simply because you can't remember what tags are available. (I know I can't ;-))

Having said that, it might indeed be more practical to have the "Tags" boxes only display already assigned tags and use *tag_suggest* to add and/or assign tags.
Not sure however if this doesn't re-introduce the _POST limitation problem of the server when you move the "Tags" boxes back to the bulk edit pages.
(I hope I understood the question correctly ;-)

@SubJunk 
> It's possible we will just disagree about it

Don't worry. Your input is very much appreciated !

**Comment by acrylian** [comment]
If you have a lot of tags assigned you surely can again run into the POST limitation. Depends on the server naturally.

**Comment by SubJunk** [comment]
@fretzl yeah you're right that you lose the ability to scroll through tags to jog your memory. I haven't ever used the list like that, but maybe I'm unusual in that way.

@acrylian @fretzl I think the POST limitation is mostly encountered because of the multiplying effect on the unused tags - if you display 10 images on one page, then each tag is being needlessly submitted ten times.
You're right that theoretically you can exceed the POST limit with just the used tags too but I don't think it's likely, especially since a server that hosts zenphoto will have to have a POST limit large enough to accept images. I think by default PHP sets the POST limit to 8MB (?) and it would be pretty amazing if a group of images used 8MB of tags unless I underestimate how many tags people are adding? I probably add about 20 tags per image at the most, so that's about 1KB per image.

Possible solutions that would restore the ability to add/edit tags on the image bulk edit page that I can think of are:

1) This PR. It has the advantage of being easy to implement, and fixes both the POST (I think) and client-side performance issue associated with having 1k+ unused tags.
2) A more elaborate fix that may let us keep the unused tags would be to do two things:
2a) Fix the POST issue by not submitting unused tags with the used ones. There is no advantage to submitting the unused ones anyway since their absence tells us the same thing as their presence. So they can be changed from checkboxes to links, and onclick JavaScript converts the link to a new checkbox.
2b) Fix the performance issue by using a jQuery database/array for the tags - so the source code only contains one instance of the tags instead of one instance per image - and the speed of jQuery fetching may be enough to not worry about the slowdown. That's just an idea though and it may end up being just as slow.

**Comment by sbillard** [comment]
The PHP default POST limit is not really the issue--the issue is that apparently many hosts reduce this limit, often to about 1-2MB.

#1: You can, of course, already add tags to images on this page via the bulk actions.
#2a: Actually, only "checked" checkboxes are posted anyway. So it is not the unused tags that would be causing the POST to be too large. But of course the set of all tags used by all the images on the page may be somewhat large.
#2b: The list of all tags IS only fetched once. And even then getting the full tag list is a pretty simple query and would be done by tagSuggest anyway. If performance is an issue then it must be fetching the set tags for each image. That can hardly be avoided, but probably it is not the problem since the current implementation is already doing that. It might also be the rendering of the HTML (host or client) for the multiple lists that is the issue.

**Comment by SubJunk** [comment]
@sbillard 1) That's less convenient in my opinion
2a) Maybe I'm ignorant of how large POST information can get but it seems to me that in order to reach even a 1MB POST limit you would need over 1 million characters to be sent, which is tens of thousands of tags. I must be missing something.
2b) The last sentence of your reply is what I think, too, so I was wondering if the browser would struggle the same amount if it were loading the HTML dynamically via JavaScript vs from the hardcoded HTML list as it is now. It may also tie in with 2a since browsers may find it easier to render link elements than form elements.

**Comment by sbillard** [comment]
I do not really know what the issue was with the bulk image page. Certainly it was solved by limiting the things that were changeable on that tab, including tabs. Any "fix" would need to be verified that it did not re-introduce the original problem. Of course it is not just the tags that get posted, they are just an additive. 

The fix that I can envision is that a "add tags" widget could be made--It would not list any tags, only let you use tag suggest (or manual typing) to add ones. Then both 2a and 2b are addressed. It would still be possible to exceed the POST limit but you would have to work at it.

**Comment by acrylian** [comment]
When I referred to the POST limit I did not only mean the memory limit hosts/servers have. There is also the `max_input_vars` limit. That should not be easily exceeded (my host has it set to 6000+ elements) but still possible that some shared hosts set it unexpectedly very low. We don't know that. Also the more fields the more memory consumed possibly on submitting (even if text is not that much…).

Before the plugin options were changed to show one only plugin's option page at the time the page was hardly usable in some browser delaying for serveral seconds.   I do remember issues reported about incomplete form submissions which is likely related to this.
As mentioned there is also JS slowing things down (the options above were quite some form elements and within a JS accordion). 

TinyMCE – although faster with v4.x – does also slow down the more fields it is attached to (especially in multilingual mode with several languages) and the same with the dirty script check script does the more fields it has to monitor for changes at once possibly.

As mentioned there is always the option to use the bulk edit options to assign tags on that page so it works without any new form elements basically. I think we won't change anything on this at this time.

**Comment by JimBrown** [comment]
The `max_input_vars` limit was introduced in PHP 5.3.9 and defaults to 1000. That is what is set on my shared host. I do believe it can be modified via php.ini.

Perhaps adding a debuglog line to log a count of the POST variables would indicate if this is an issue...

Regards,
...jim

**Comment by sbillard** [comment]
There is a test to see if the post is truncated--not the same as a count, but does tell us if the post failed. That was what lead to removing the tags from the multi-item pages.

**Comment by SubJunk** [comment]
@acrylian no problem :) For my websites that use a mix of zenphoto/zenphoto20 I'll continue to use this PR because I think it's important for an interface to be as simple as possible by default; requiring any extra clicks for tag editing isn't good for me, but I understand that you have to err on the side of caution with regards to server limits.

@sbillard the commit you did could be a good compromise. I don't see any downside in listing the existing tags along with that commit - they don't have to be part of a form, and the code already exists in admin-edit.php:1361.

**Comment by sbillard** [comment]
Take a look at the latest master. The tags are listed, all be in in free form when the shortened entry mechanism is shown.

**Comment by acrylian** [comment]
@SubJunk Since we do list the already assigned tags we could probably just provide a means to add new ones via tag_suggest as a compromise indeed as well. I will take a look at that (and I don't mean the fork code).

**Pull request closed without merging**
