### PR TITLE
Remove registered custom size no longer used

### PR DESCRIPTION
**Pull request by JesseHC**
#1383

### CODE REVIEW

**Comment by acrylian** [comment]
I don't think this is correct. The themes do use their own custom sizes so they must be registered to be pre-cachable. They cannot just be replaced by defaultt sizes because those are not even used. 

Also a theme may of course also register sizes for plugins. Of course they can register thteir own sizes but theme plugin can be overriden and set via the them. So they must also be registered if custom. Just using default sizes is wrong as well

The only concern seems to be that these are editable in tthe cachemanger settings. That is another issue and needs to be address. Probably sizes registered via themes or plugins should not be editable at all because they are of course registered for a reason.

**Comment by acrylian** [comment]
> I don't think this is correct.

The size of Basic theme seems to be a correct one to remove though.

**Comment by sbillard** [comment]
If someone edits or deletes one of these theme/plugin defined cache sizes it will just be replaced next time setup is run or the theme options get saved.

**Comment by JesseHC** [comment]
> I don't think this is correct. The themes do use their own custom sizes so they must be registered to be pre-cachable. They cannot just be replaced by defaultt sizes because those are not even used.

By adding the values as:

```
cacheManager::addDefaultThumbSize();
cacheManager::addDefaultSizedImageSize();
```

like Basic _was already doing_, they are declaring the values set in themeoptions, either by the existing default value or by the value added by the user, as the new defaults to use. cacheManager will then cache these sizes, even the custom sizes set in the options by the user. You can easily test this, but also, Basic has been doing it like this all along. The only thing changed on Basic was removing the registered size not used.

When you run cacheManager, this is what you will see by default now with my changes, and the custom theme sizes will still be created.

cacheManager new default

The real issue with this is that the other included themes have not been doing it like Basic. They were being inconsistent, and should have matched how Basic was doing it. By registering the new sizes instead of adding them as `addDefaultThumbSize()` and `addDefaultSizedImageSize()`, they were being redundant, but also adding to potential user confusion for the extra registered sizes and opening themselves up to issues if they changed those sizes in cacheManager.

They were also being inconsistent, and possibly added extra unnecessary sizes, where zenpage registered the image size with hardcoded values, but used `addDefaultThumbSize()` for the thumbs. ZPmobile did the exact opposite, `addDefaultSizedImageSize('zpMobile')` for the image and hardcoded the values for the thumbs.

Garland registers sizes for both images and thumbs.

The thing is that image and thumbnail sizes were disable in all three theme options, so there was no way the user could change them. Actually, by additionally registering the sizes, they opened themselves up to being edited in cacheManager and causing problems.

> Also a theme may of course also register sizes for plugins. Of course they can register thteir own sizes but theme plugin can be overriden and set via the them. So they must also be registered if custom. Just using default sizes is wrong as well

Yes, of course a theme should be able to add a custom size. For instance, if a theme was using HiDPI images, where it would need 2x, and possibly 3x sizes, or if an image page was using custom next image previews different than standard thumbnails, but none of the included themes are doing this. It appears they are all using standard images and thumbs that don’t need separate registered sizes, and nothing is needed for custom plugin sizes.

All of the changes I made can easily be tested to see if they work, and as far as I can tell, they do!


> The only concern seems to be that these are editable in tthe cachemanger settings. That is another issue and needs to be address. Probably sizes registered via themes or plugins should not be editable at all because they are of course registered for a reason.

Yes! There should also be sizes that are registered that should not be editable. Such as the HiDPI example listed where sizes would be locked to 2x and 3x the image values set, so they should not be changed.

> If someone edits or deletes one of these theme/plugin defined cache sizes it will just be replaced next time setup is run or the theme options get saved.

Not so with the changes I made. They will all be handled like the current Basic theme (minus the one extra size that was removed).  The registered sizes will automatically be removed from cacheManager and will not appear if setup is run or theme options are saved.

**Comment by acrylian** [comment]
Proofs my point that basically no registered sizes should be editable at all. 

Actually the whole interface concept is a rather ill concept. Because editing a size without editing the theme or plugin code calling it is pointless as well. If someone customizes coded sizes on a theme or plugin already it is far better to just change or add the registration for that size as well. If pre-caching is necessary for the type of site (which for smaller sites IMHO is still not)

For the same reason manually added custom sizes that are not reflected in code are rather pointless, too.

A plugin that has image size option should instead self re-register these changes like the default sizes are currently. Which probably no plugin does currently. But that is another point.

> like Basic was already doing, they are declaring the values set in themeoption
> The real issue with this is that the other included themes have not been doing it like Basic. They were being inconsistent, and should have matched how Basic was doing it. 

It is rather pointless to register default sizes to a theme like Zenpage which does not use them at all because it uses hardcoded custom sizes for layout reasons. Which is also why the standard theme options for these are disabled.

These themes are old, technically outdated and deprecated.

>  For instance, if a theme was using HiDPI images, where it would need 2x, and possibly 3x sizes,

Responsive image extra sizes will be covered by core in the future.

**Pull request closed without merging**
