### PR TITLE
zenphoto.js only served to logged users

### PR DESCRIPTION
**Pull request by Simounet**
Hi,
I've already look at #957 and I may be wrong but I would like to avoid the use of this script if we doesn't need it.

Have a nice day and thanks for this amazing tool!

### CODE REVIEW

**Comment by acrylian** [comment]
We will take a look at that, it is really legacy one we need to review anyway.

**Comment by Simounet** [comment]
I understand. I'm just trying to improve the performance of my theme so I'm removing unused stuff.

**Comment by acrylian** [comment]
Yeah, I get that point ;) Probably we can do this. Will try to take a look soon.

**Comment by acrylian** [comment]
I fear it is not that easy. Function from that are used in some login links and are needed if you are not logged in if I see correctly. This is old stuff and I think we will not change this now in 1.4.x anymore.

**Pull request closed without merging**
