### PR TITLE
Patch 6

### PR DESCRIPTION
**Pull request by kochs-online**
This should fix the problem described in #1362.

### CODE REVIEW

**Comment by kochs-online** [comment]
Not completely sure how to handle tags using exp(). My changes will prevent a TypeError, but the returned value will not be very meaningful because exp() cannot be called for a string.

**Comment by acrylian** [comment]
Thanks. I am not familiar with the exact values. But couldn't we just make them numbers first or are they really strings occasionally?

**Comment by kochs-online** [comment]
Yes, `unRational()` gets called with 8 bytes (2 integers). The first is the numerator of a rational value and the second is the denominator. If the second integer is 0 `unRational()` will return a string (e.g. "4/0") because it cannot calculate an irrational value when dividing by 0.

**Comment by acrylian** [comment]
Okay, thanks, I will take this in.

**Pull request merged**
