### PR TITLE
Surpress error messages of imagecreatefrom...()

### LINKED ISSUE #1158: debug.log: imagecreatefromjpeg() failed
I noticed a couple of entries in the `debug.log` file that are related to uploading invalid JPEG images, I think. I'm running Zenphoto version 1.4.14.

Without further ado – here are the `debug.log` entries:
```
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error:  in /home/www/zenphoto/zp-core/lib-GD.php on line 91
  imagecreatefromjpeg called from zp_imageGet (lib-GD.php [91])
    from cacheImage (functions-image.php [197])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: imagecreatefromjpeg(): '/home/www/zenphoto/albums/example-album/invalid.jpg' is not a valid JPEG file in /home/www/zenphoto/zp-core/lib-GD.php on line 91
  imagecreatefromjpeg called from zp_imageGet (lib-GD.php [91])
    from cacheImage (functions-image.php [197])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: Cannot modify header information - headers already sent by (output started at /home/www/zenphoto/zp-core/lib-GD.php:91) in /home/www/zenphoto/zp-core/functions-image.php on line 30
  header called from imageError (functions-image.php [30])
    from cacheImage (functions-image.php [200])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: Cannot modify header information - headers already sent by (output started at /home/www/zenphoto/zp-core/lib-GD.php:91) in /home/www/zenphoto/zp-core/functions-image.php on line 31
  header called from imageError (functions-image.php [31])
    from cacheImage (functions-image.php [200])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: Cannot modify header information - headers already sent by (output started at /home/www/zenphoto/zp-core/lib-GD.php:91) in /home/www/zenphoto/zp-core/functions-image.php on line 32
  header called from imageError (functions-image.php [32])
    from cacheImage (functions-image.php [200])
      from i.php [165]
```

Nothing major, but error handling might be improved here because it took me quite some time to figure out why the image didn't show up.

### PR DESCRIPTION
**Pull request by kochs-online**
Seems to fix #1158

### CODE REVIEW

**Comment by acrylian** [comment]
Yes, using `@` is a hotfix. But sorry I will not pull this in. I know Zenphoto uses the `@` way for pragmatic reasons all over the place. But actually it also kills error messages itself so you sometimes don't even know that something doesn't work. It is on the list to review all these usages sometime and perhaps better use `try/catch` calls if possible instead.

**Comment by kochs-online** [comment]
We could use [`error_get_last()`](https://php.net/manual/function.error-get-last.php) to get the most recent error message. What would be the correct way to handle such an error message in Zenphoto?

**Comment by kochs-online** [comment]
What about something like this:
```
function zp_imageGet($imgfile) {
	$res = false;
	$ext = getSuffix($imgfile);
	switch ($ext) {
		[...]
		case 'jpeg':
		case 'jpg':
			$res = @imagecreatefromjpeg($imgfile);
		[...]
	}
	if (false === $res && DEBUG_IMAGE) {
		$err = get_error_last();
		if (is_array($err))
			// e.g. Error: imagecreatefromjpeg(): '$imgfile' is not a valid JPEG file (lib-GD.php:91)
			debugLog("Error: $err['message'] ($err['file']:$err['line'])");
	}
	return $res;
}
```

**Comment by acrylian** [comment]
I am still not sure if we really need this since that is what already happens for me with invalid images: 

`[23-Jun-2018 14:39:08 UTC] PHP Warning:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error:  in …/zp-core/lib-GD.php on line 92
[23-Jun-2018 14:39:08 UTC] PHP Warning:  imagecreatefromjpeg(): '…/albums/testimages/i-am-no-jpeg.jpg' is not a valid JPEG file in …/zp-core/lib-GD.php on line 92 `

So I already get all info needed to fix this issue. try/catch would do the same actually but since there is already a proper error/warning. And remember I also get the broken placeholder.

bildschirmfoto 2018-06-23 um 16 42 02

**Comment by kochs-online** [comment]
But doesn't it also break the album?

> Such really corrupt image is meant to cause trouble and kills the whole album on our own site with the same errors you got.

**Comment by acrylian** [comment]
It does not break the album for me. However on our demo it does indeed not load the replacement image but still doesn't break the album itself. Take a look:
https://demo.zenphoto.org/test/

**Comment by acrylian** [comment]
I will reject this for now.

**Pull request closed without merging**
