### PR TITLE
openstreetmap: markers styling and new options

### PR DESCRIPTION
**Pull request by kuz-z-zma**
- Added missing `title` attributes to Image page links for markers on the map (title & thumb)
- Added classes for styling of title and thumbs for markers on the map (`openstreetmap-thumb`, `openstreetmap-title`)
- Added missing `alt` attribute to thumbs for markers on the map
- Removed trailing `<br>` after titles in thumbs (unnecessary, if need be - styling can be done with CSS now)
- Added option to specify `length` of title displayed for markers on the map.
- Added option to specify `length` of descriptions displayed for markers on the map.
- Added option to choose Default thumb or a Custom sized image to be displayed in markers on the map.
- Added option to specify the `width` of custom image, used as thumb.
- Changed default Custom image `width` to **120px** (to remove resizing of it's width by default CSS file)
- Removed `width` from default CSS file for images, to allow user to use smaller thumbs (with changed default size resizing via CSS is now unnecessary)
- Added option to disable usage of default CSS file, to allow for redesign of popup markers.

### CODE REVIEW

**Comment by acrylian** [comment]
Sorry; I have some comments once again ;-):

Most important: I will not pull this in for 1.6.4 anymore but after the release. Actually we/I already wanted to have released but "real work" prohibited me a little from doing so. All (most ;-) changes are good but rather "nice to haves" than pressing needed. 1.6.4 needs to get out because of the user account bug and because of new options we need translation updates not all might be able to do on that short notice.

Now to tthe actual comments:

- Not sure about the necessity of title truncation but for the description it is certainly a good idea
- Image options look good
	- But we should keep 150 as default because otherwise all existing sites will have unnecessary extra image sizes and uncached images. The file size difference between a 120 and 150 image is rather small. Images should generally be set to be responsive so they adjust to the popup without exceeding their original size instead. The usual code which normally should be set via a theme but of course our old themes don't: max-widht: 100%; height: auto: display: block; So IMHO we stil need the openstreetmap.css file for this because themes - certainly not ours - may not handle that.
	- Size registration is not yet correct. Currently the default value is hardcoded but we need to also use the option if changed and a definition switch if the default thumb is used becuase the custom definition then is not needed
	- I am not so sure about disabling the default css from leaflet and its addons. Most people will not even bother to do so. So perhaps keep options to the absolute necessity and use custom css for changes instead.
	- Also changes to leaflet.css will for sure be overridden by the next leaflet update. We use third party libraries as they are provided. For needed adjustments there was the openstreetmap.css or the theme.
	- (Sidenote: We preferredly don't use ORDER in options anymore but just define the options in the order as needed. We just haven't updated most things so this would also be an occasion for that;-))
	
Sorry for the comments. I really appreciate the work!

**Comment by kuz-z-zma** [comment]
> Most important: I will not pull this in for 1.6.4 anymore but after the release. 

It's fine with me, maybe I'll get time to utilise those features for the layout I have in mind and additionally change or add something.

> Not sure about the necessity of title truncation but for the description it is certainly a good idea

Title/desc truncation were there, but inability to adjust it to one's liking is frustrating. I generally object at anything hardcoded in, when there are options - this promotes creative thinking.
50 and 100 characters is just too short for Russian, for example.

> Image options look good
> But we should keep 150 as default because otherwise all existing sites will have unnecessary extra image sizes and uncached images. The file size difference between a 120 and 150 image is rather small. Images should generally be set to be responsive so they adjust to the popup without exceeding their original size instead. The usual code which normally should be set via a theme but of course our old themes don't: max-widht: 100%; height: auto: display: block; So IMHO we stil need the openstreetmap.css file for this because themes - certainly not ours - may not handle that.

I think, I saw someone deleting obsolete cache sized images via options - can it be added, to force regeneration without left-over 150px thumbs?

Writing width in px for the image in openstreetmap.css prevents users from using a smaller one - for example, 80px. It forces smaller sizes to be stretched out. 

> Size registration is not yet correct. Currently the default value is hardcoded but we need to also use the option if changed and a definition switch if the default thumb is used becuase the custom definition then is not needed

I've added that for `getImageGeodata` or what switch do you mean?

> Also changes to leaflet.css will for sure be overridden by the next leaflet update. We use third party libraries as they are provided. For needed adjustments there was the openstreetmap.css or the theme.
> I am not so sure about disabling the default css from leaflet and its addons. Most people will not even bother to do so. So perhaps keep options to the absolute necessity and use custom css for changes instead.

This is an option for those who design themes or want to do some serious customisation and know what they are doing.
It allows to forget about changes to the leaflets and it's addons - by disabling them altogether.
Extensive custom CSS I can add via theme is overruled by those default css files for openstreetmap, as they are listed later in the `head`, so for the theme author to do anything major with markers - you have to disable all of them and after copying over their content to your own file - rework it to suit your vision. 
I thought about allowing user to select custom css file, or enter css directly through the textarea option - but then we ran into the question of sharing those settings with users of your theme, for example. 
Instructions will change from "disable 1 setting" (which I can attempt do via theme options even) to "upload file, select here or go there and enter following code", not very user-friendly.
I might add the option to add your custom css file though, for those who use themes without ability to add custom css files easily.

But yes, as you have said - most people won't bother and will be content with using default CSS files (so this option is enabled by default), small changes can be done via entered image sizes and added classes for title and thumb.

> (Sidenote: We preferredly don't use ORDER in options anymore but just define the options in the order as needed. We just haven't updated most things so this would also be an occasion for that;-))

You should start the the switch to this practice with update to demo-plugin and demo-theme then, to let people know about it - I certainly wasn't aware of it.

**Comment by kuz-z-zma** [comment]
Example of current hardcoded 120px for img inm CSS when using 80px custom sized image.

80px with css with removed width in pixels, works as expected

Screenshot_49

current version of css attempts to stretch 80px to 120px and my css overrides won't be applied due to position of css links in the `head` without disabling all default css files or replacing openstreetmap.css file after each and every upgrade. 

Screenshot_51

**Comment by acrylian** [comment]
> I think, I saw someone deleting obsolete cache sized images via options - can it be added, to force regeneration without left-over 150px thumbs?

No, you have clear the image cache and regenerate everything. You cannot just clear one size.

> Writing width in px for the image in openstreetmap.css prevents users from using a smaller one - for example, 80px. It forces smaller sizes to be stretched out.

I am not talking about hardcoding a px site. I explicitly referenced common responsive image css without px above:
 `max-width: 100%; height: auto: display: block;`

That makes an image fit into the container without exceeding its original size. So 120px wide image will be made smaller if the popup is 100px wide but not larger if the popup is 200px wide. Any proper responsive theme should have set this of course anyway.

> I've added that for getImageGeodata (commit [e1437f0](https://github.com/zenphoto/zenphoto/pull/1447/commits/e1437f06c4f1145969d5292a2eb6aa75edcf6a1d)) or what switch do you mean?

I am referring  to the registering of the image size for cacheManager right within the constructor. That is hardcoded to 120 now no matter what the image size is set. If the thumb default size is selected it must not even be registered because then not used at all.

> I thought about allowing user to select custom css file, or enter css directly through the textarea option - but then we ran into the question of sharing those settings with users of your theme, for example.

I seriously think that this overloadss the plugins. I am pretty sure the majority of our (few) users will just use it as it is.  Who really wants to create a theme and even taking the work to customized the map css really finds other ways. 

> I might add the option to add your custom css file though, for those who use themes without ability to add custom css files easily.

Several plugins have custom css options via the /plugins folder.

We may have better ways in the future at some time… We actaully like to limit "nice to have" changes in 1.x in generally quite a bit because due to "porting hell" that all will delay work on the major release further and further. We are restructuring a lot of things so we even cannot always just copy stuff over.

**Comment by acrylian** [comment]
I will perhaps pull this in after the metadata issues are fixed. Before that I have no time to review and adjust a few things as discussed above this will not be include as it is.

**Comment by kuz-z-zma** [comment]
I will look into cached sizes and other stuff as discussed too, was sick and couldn't focus on it those weeks - maybe it will be better prepared for pulling in by the time you get to it.

Thank you though, would really appreciate any help if I miss anything or if there is a better way of going about stuff.

**Comment by acrylian** [comment]
No problem. After all this is all rather "nice to have" in general and therefore not urgent ;-)

**Comment by kuz-z-zma** [comment]
I've rolled back the default custom image size to 150px, so existing users are not forced to regenerate their cached images
+ added some clarification to options.

**Comment by acrylian** [comment]
Great, thanks. As mentioned before the note about custom images  being larger than 120px is actually if the default CSS set images to be responsive as they then will fit in the popup: 

     img  {
       max-width: 100%;
       height: auto;
       display: block;
     }

**Comment by acrylian** [comment]
This means either openstreetmap.css needs to return, we have to add it via a `<style>` part or even "ugly" via inline style.  This has to work in any theme by default.

**Comment by kuz-z-zma** [comment]
You know, I look into it and I think, I should rollback my rollback.

We are generating a specific custom image size that's exceeds the allocated space for no reason at all --> therefore we are forced to include a CSS file to address that --> and this CSS file prevents us from giving a user means to change presentation themselves easily.
One forced regeneration vs dragging this choice of 150px size further for no good reason.

We already have 2 inline styles hard-coded into presentation (one by for div id="osm_map" and one by leaflet script):
Screenshot_vivaldi_2024-07-28-01 37 25

**Comment by acrylian** [comment]
> You know, I look into it and I think, I should rollback my rollback.

Don't see any reason as we still don't want to cause re-generation of the image. 30px too much more do not really do any harm., not even in file size. and it can be changed via an option anyway.

> We are generating a specific custom image size that exceeds the allocated space for no reason at all --> therefore we are forced to include rules in the CSS file to address that --> and those CSS rules file prevents us from giving a user means to change presentation themselves easily.

I still think this is really a niche request. The majority of users will (and should be able) to use this as it is as they do with theme. 

> We already have 2 inline styles hard-coded into presentation (one by for div id="osm_map" and one by leaflet script):
The leaflet inline style is not of our concern and it even may be added/changed dynamically via JS. Our one on the map wrapper is necessary as otherwise we cannot set the map width via an option. For granted you can argue if that is necessary as for 99,9% of everything just a responsive max-width: 100% is fine. Themes can change it via custom wrappers if needed or via CSS override (yes, with !Important then but well…)

THe old openstreetmap.css was not perfect and old but addressed a few things the leaflet ccss doesn't. Actually the popup itself should be responsive and on small width fit within the width. If you really don't like the default css you can disable it via a filter, too.

**Comment by kuz-z-zma** [comment]
I've rolled back, my initial stand is more usefull, I think.
We are using 150px for no reason.

I wholly agree that this should work out of the box, but current setup prevents any usefull changes to be made by those wanting to. 
My gripe with 150px is not the filesize, but the fact that it is a specific width used in a popup that's now is a fixed size and since it's bigger - we are forced to include rules in the CSS file to shrink the image and this rule (width:120px!important) can't be overridden easily by themes, due to the position of openstreetmap.css in the head section of the Zenphoto site.
If we change to using 120px thumb - we can safely delete this rule and open up the way to customize thumb sizes and presentation.

I would even argue that defining pop-up width in openstreetmap.css should be removed, to allow for fluidity:

Current:
```
.leaflet-popup-content {
	min-width:120px!important;
	max-width:120px!important;
	width:120px!important;
	}
```

More usefull and open to customization:
```
.leaflet-popup-content {
	min-width:120px!important;
	}
@media (max-width: 550px) {
.leaflet-popup-content {
	max-width:120px!important;
	}
```

My example.
Proposed changes on my demo site: https://demo.private-universe.net/hinterfolk/hinterfolk.jpg.html
Here I'm using 80px custom size thumb and have disabled default CSS styles, so I can float thumb to the left and make a wider pop-up to incorporate text - those seem to be very basic changes, but are surprisingly hard to achieve right now.

Why all this -  I was trying to make a layout to use for travel photography and wanted a bigger map as a main feature, with pop-ups that are more suitable for displaying text.

**Comment by acrylian** [comment]
I do generally get your point. My concern about the changed default size is just the new generation of images. On  1000 image site with geodata this means 1000 additional images  and 1000 obsolete. Which is in general why it is an option now, too.

Regarding the CSS. As mentioned it is pretty old and could perhaps even be even simpler:

       // Not sure about the min-width as you don't want popups to be too large, right? 
       // This should make it responsive to the map width (if leaflet itself lets us do that);
      .leaflet-popup-content {
	max-width:120px!important;
	}
       // this should be added in any case so the image never exceeds the popup, if that really gets responsive.
      .leaflet-popu-content  img {
           max-width: 100%,
           height:auto;
           display: block;
       }

Regarding default CSS my whole concert was that you - if I recall right - also made the core leaflet CSS disabable. I have no problem making our openstreetmap.css one as that certainly is additional.

**Comment by kuz-z-zma** [comment]
> On 1000 image site with geodata this means 1000 additional images and 1000 obsolete.

One time event that can be noted in the notes for the release - so people can delete obsolete images.
Аs I understand - new cache sizes can be generated automatically upon first request.

> .leaflet-popup-content {
> max-width:120px!important;
> }

I actually want to make them wider, therefore want to at least omit width and restrict max-width usage for cases when it's needed - mobile, etc. But, for the sake of backward compatibility - can be left as is, since next option allows to disable all of it and rewrite css styles completely. 

Basically, I think that openstreetmap.css should cater to people who want minimal changes to their presentation - allow for smaller/bigger image thumb, allow for longer text from description... 

> Regarding default CSS my whole concert was that you - if I recall right - also made the core leaflet CSS disabable. I have no problem making our openstreetmap.css one as that certainly is additional.

Disabling of leaflet.css, MarkerCluster and MarkerCluster.default.css  - they have a lot of weird margins and other presentation stuff, and as they are located below theme css files in the head section - they overwrite user changes, so the only way to get full control is to disable them, copy all that stuff into your own css file and rework as needed without concerns about css rules conflicts, cancelling each other out, etc.

As I wrote somewhere above - another option would have been ability to add your own css file/code in the options, but I feel that will not get much use, as people who might want to do that are theme creators/designers, and it makes sense to keep elements of your site design in with the theme files - easier to maintain, easier to share with others.
It's easier to tell people "disable this option" or disable it via theme configuration,  than ask them to upload additional files, enter code...

I've added more detailed description for this setting, with a warning, list of files it disables and instructions what to do.

**Comment by acrylian** [comment]
> One time event that can be noted in the notes for the release - so people can delete obsolete images.
Аs I understand - new cache sizes can be generated automatically upon first request.

Yes, first visit will create a new image. But there is no way to remove the old generated images not needed anymore. You would have to clear the whole image cache. 


> I actually want to make them wider, therefore want to at least omit width and restrict max-width usage for cases when it's needed - mobile, etc. But, for the sake of backward compatibility - can be left as is, since next option allows to disable all of it and rewrite css styles completely.

We can make the width of the popup an option. That probably would have to be done via `<style>` section though.

> Disabling of leaflet.css, MarkerCluster and MarkerCluster.default.css - they have a lot of weird margins and other presentation stuff, and as they are located below theme css files in the head section - they overwrite user changes, so the only way to get full control is to disable them, copy all that stuff into your own css file and rework as needed without concerns about css rules conflicts, cancelling each other out, etc.

Yes, plugins generally load after the theme so their defaults work (if a theme sets too general styles it can kill plugin styles completely, we had this several times). Of course those have presentational styles as otherwise those probably won't work and there is a lot of dynamic styling via JS involved I am sure. I have not investigated as I never had any desire to adjust anything except the popup in general… 

It should be technically possible to remove the CSS via  `zp_remove_filter()`, too. Haven't tried of this works via the them or require another plugin in this case. We can leave that option in if you insist but I still think the map is the least plugin anyone will want to do that :-)

**Comment by kuz-z-zma** [comment]
> But there is no way to remove the old generated images not needed anymore. You would have to clear the whole image cache.

That's what I meant - putting a notice that the default size thumb was changed to offer more flexibility, tell people to check their settings and delete unwanted cache.

> We can make the width of the popup an option. That probably would have to be done via <style> section though.

I don't think that's a good idea.
Adding any additions via plugin options into a <style> section here just feels wrong - all the design alterations for the frontend should be in the css file(s) for the theme the site uses...
And the default css should give some wiggle room for the most common needs, so you don't have to disable them altogether unless you are going for a very specific look.

> We can leave that option in if you insist but I still think the map is the least plugin anyone will want to do that.

The basic design is solid and unobtrusive, and it works just fine, until you DO want to do something with it, and then you find all those css files that won't allow you even the smallest basic edits without throwing up some weird stuff into the mix. 
Also, if someone wants custom icons - no way to replace them (and keep them safe from overwrites upon updates) otherwise.
So yeah, I insist on an option to disable default leaflet css files.

**Comment by acrylian** [comment]
> That's what I meant - putting a notice that the default size thumb was changed to offer more flexibility, tell people to check their settings and delete unwanted cache.

Okay.

> I don't think that's a good idea.
Adding any additions via plugin options into a <style> section here just feels wrong - all the design alterations for the frontend should be in the css file(s) for the theme the site uses...

I agree, it should be done via CSS files in any case.

> Also, if someone wants custom icons - no way to replace them (and keep them safe from overwrites upon updates) otherwise.

You mean the marker icons? You actually can do that without. Not with our plugin itself but with custom leafletjs code of what we provide via printMap().

> So yeah, I insist on an option to disable default leaflet css files.

;-)

**Comment by acrylian** [comment]
FYI I have updated some scripts: Leaflet 1.9.4 and leaflet-providers 1.13.0. Should probably not cause trouble but please test @fretzl

**Comment by fretzl** [comment]
After the update the map doesn't show any markers and the zoom is way off.

Before:
before

After:
after

And I have this in the browser console:
Scherm­afbeelding

**Comment by acrylian** [comment]
In any case  forced cleared you browser cache. I had first a totally broken map all over the window because it still used the old versions from cache.  It looks pretty normal for me on my test album:

Bildschirmfoto 2024-08-12 um 19 21 35

**Comment by acrylian** [comment]
Regarding the providers issue: I updated the leadlet-providers.js file. Don't remember how that is used but we another list in the method getTileProviders() that perhaps contains providers not available anymore and enabled. Perhaps one is selected and does not match anymore… I just have the mapnick default one and have no error so far.

**Comment by fretzl** [comment]
It all works again when I disable _GeoportailFrance.ignMaps_ and _GeoportailFrance.orthos_ in the _Layers list_ option.

**Pull request merged**
