### PR TITLE
Fixes for comment form quiz fields

### PR DESCRIPTION
**Pull request by bic-ed**
The error message part has to be discussed.

One more thing to clarify is that, since no verification on quiz fields is done for logged users with post comments rights, we should either:

1. Remove the required attribute for logged users
2. Remove the input fields from the form for logged users
3. Perform the verification, no matter what

We could also add, like for the Capcha field, a "For guests" option to quiz fields,

### CODE REVIEW

**Comment by acrylian** [comment]
I am a bit confused the first parts I thought I already had committed in a similar form already… Anyways. If a user is loggedin we can assume he is known so we can really skip these fields (not sure why captcha has an exception actually). THe easiest would be to hook into getQuizFieldQuestion() and return nothing if logged in. That would cause them not to be shown and since they are not checked anyway all should work, right?

**Comment by bic-ed** [comment]
> I am a bit confused the first parts I thought I already had committed in a similar form already…

If you mean the error messages, I just added a space before them and a dot after, to have items displayed into different `<li>` elements. This is the resulting output.

immagine

As you can see it is still missing something before, such as "Please enter"...

> THe easiest would be to hook into getQuizFieldQuestion() and return nothing if logged in. That would cause them not to be shown and since they are not checked anyway all should work, right?

Yes, the more logical thing would be to remove the quiz fields  for logged users.

**Comment by acrylian** [comment]
So quickly looked. Yes, those meessage were taken from the contact form and need to be full sentences here as all others are. 
Bildschirmfoto 2024-08-02 um 15 25 28

**Comment by bic-ed** [comment]
> Haven't check that but that seems something is missing. I referred to these that are labeled as new:
> 
> Bildschirmfoto 2024-08-02 um 15 23 54

Those were actually missing

**Comment by acrylian** [comment]
> Those were actually missing
I just looked indeed my commits  - Seems I partial committe comment form stuff but didn't label it -  does not have those partial message according to github. But my local backup from Sunday does have those already as you committed them…

I guees I need to re-checkout the repo, I always have to fetch before I can commit for a while now. Apparently that causes trouble…

**Pull request merged**
