### PR TITLE
Fix guest login for zenpage items

### PR DESCRIPTION
**Pull request by bic-ed**
Partially solves #1332

### CODE REVIEW

**Comment by bic-ed** [comment]
I know that for regular zenphoto objects there is no need to declare $hint as global, but for zenpage objects for some reasons doesn't work the same way.

PS
It would be nice to extend the $show parameter to zenpage items too...

**Comment by acrylian** [comment]
> I know that for regular zenphoto objects there is no need to declare $hint as global, but for zenpage objects for some reasons doesn't work the same way.

I would prefer to exclude the global part for now.  And if var names would have to follow naming conventions anyway ($_zp_hint or even better $_zp_passwordform_hint instead of $hint).

> It would be nice to extend the $show parameter to zenphoto items too...

That we probably can investigate later.

**Comment by bic-ed** [comment]
> I would prefer to exclude the global part for now. And if var names would have to follow naming conventions anyway ($_zp_hint or even better $_zp_passwordform_hint instead of $hint).

Do you have a clue why regular zenphoto items do not need global $hint while zenpage items do?

**Comment by acrylian** [comment]
No, would have to investigate that. Should be the same for all actually…

**Comment by bic-ed** [comment]
Also, actually for single news from protected category $hint and $show are regularly passed to password form, no need for global declaration.

I'll roll back the global declarations for now then...

**Comment by bic-ed** [comment]
Looking further into it, it turned out that for zenphoto items AND for single news articles the checkForGuest() function used is the one from template-functions.php, while for zenpage pages and categories is used the static function checkForGuest() from inside the class zenpagecms in zenpage.php. I guess that's the reason why $user is not passed to password form by categories and pages.

To test it, I have moved all into template-functions.php and it works fine, so I could fix it, but I guess there is a god reason to keep thinks separated between zenphoto and zenpage items , even if it has not been done for single news articles.

**Comment by acrylian** [comment]
Especially if articles already use the main one the reason for this separation may just be that it has been forgotten at one time…  Of course some context checks for Zenpage are not available if it is off. But it should all be done in a central generalized place. Zenpage is deeply integrated in many places anyway. Let me take a look first as soon as I can.

**Comment by bic-ed** [comment]
Have a look at it, but keep in mind that if you wish I can already pull the "centralized" solution with also a fix for the $show parameter that currently is not working properly for protected zenphoto items like albums, search and gallery.

**Comment by acrylian** [comment]
I just want to be sure we don't miss any non obious reason for the separation. Your change looks good. Except: Never instantly remove functions or methods without deprecating them first using deprecationNotice() (new in 1.6a). Internally it of course should use the general function so it still works.

**Comment by bic-ed** [comment]
>Except: Never instantly remove functions or methods without deprecating them first using deprecationNotice() (new in 1.6a). Internally it of course should use the general function so it still works.

Ah yes, you mean that some theme or plugin could use that removed function directly? 
I'm unsure how to manage the deprecation notice though, I'll have a look at some existing ones.

**Comment by acrylian** [comment]
> Ah yes, you mean that some theme or plugin could use that removed function directly?

Yes, no one should probably but you never know what custom code might do. I think I cannot skip that one file change so if you just update your PR to keep the Zenpage method I can handle the deprecation part later.

**Comment by bic-ed** [comment]
Can I just keep an empty function? If I keep the whole function and the filter the fix doesn't work, because I guess the static function is executed again after the centralized one.

**Comment by acrylian** [comment]
You can just keep the method as it is - I handle the deprecation stuff - and just remove the filter call using it as that is of course obsolete now.

**Comment by bic-ed** [comment]
Ok, done.

**Comment by acrylian** [comment]
Thanks, will look into taking it in tomorrow!

**Comment by bic-ed** [comment]
The latest commit should complete fix #1332

**Comment by acrylian** [comment]
Thanks. that looks pretty simple even!

**Comment by bic-ed** [comment]
It is! I was looking in the wrong places :-)

**Pull request merged**
