### PR TITLE
Italian translation and an updated translatable string

### PR DESCRIPTION
**Pull request by bic-ed**
Hi, I'm not committing the translation myself this time, because I'm also suggesting a small change in a translatable string for the `related_items` plugin.  
As you can see, the "_Related_" text for the "_all_" case is somehow incomplete. I feel it might be better to use "_Related contents_"

### CODE REVIEW

**Comment by acrylian** [comment]
The simple "related" for "all" was (changed) on purpose actually because that general term seemed to fit for us. Of course it is "related content" because all is "content" in any case, so why double the obvious? Does that make sense? @fretzl

**Comment by bic-ed** [comment]
Ok, I'm probably biased by the Italian translation, which has to be "Contenuti correlati", because "Correlati" alone sounds really bad in Italian. Not a problem, if is ok for you like it is now, I'll remove the correction and add the rollback to this pr to leave the translation only.

**Comment by acrylian** [comment]
It's absolut okay to translate more literally if the "exact" translation does not really work in a language. I do that often in German as well. T

**Comment by acrylian** [comment]
I did mean "not literally" but more "freely" of course.

**Comment by fretzl** [comment]
> Of course it is "related content" because all is "content" in any case, so why double the obvious? Does that make sense? @fretzl

Yes, I think it makes sense.

**Comment by bic-ed** [comment]
Ok, rolled back my change, I'm merging the translation.

**Comment by acrylian** [comment]
Great, thanks!

**Pull request merged**
