### PR TITLE
Some RSS feed fixes

### PR DESCRIPTION
**Pull request by bic-ed**
Page feed was not working because of relative links in the output.

### CODE REVIEW

**Comment by bic-ed** [comment]
I was also wondering why feed links are build using `PROTOCOL . '://' . $this->host` for protocol and host and not just the `FULLWEBPATH` constant

**Comment by bic-ed** [comment]
> If FULLWEBPATH works in this case, we should go with it for now in general. A parameter would not be that hard to add.

I was wrong, I see that host in the RSS class is set as
`$this->host = html_encode($_SERVER["HTTP_HOST"])`
while FULLWEBPATH is `define('FULLWEBPATH', SERVER_HTTP_HOST . WEBPATH)`
where SERVER_HTTP_HOST is `define('SERVER_HTTP_HOST', PROTOCOL . "://" . $_SERVER['HTTP_HOST']);`

feed/RSS classes are using `PROTOCOL . '://' . $this->host`

So they are not the same at the end, they differ for the encoding on $_SERVER['HTTP_HOST'] and for the WEBPATH.
Actually `PROTOCOL . '://' . $this->host` could probably be replaced by `html_encode(SERVER_HTTP_HOST)` to have exactly the same thing, if it worth the effort.

**Comment by acrylian** [comment]
Looks weird a little what we do here ;-) Either there was some reason for this I don't remember or something was forgotten. I think the SERVER_HTTP_HOST constant is newer and was specifially because some issues with the protocol…

**Comment by bic-ed** [comment]
Yes, I'd leave paths as they are for now, just using this fix for pages. Then if you think is important we can change the protocol part all together across the feed code.
There are a few more things to be addressed here though, if you wish we can discuss about that by mail, leaving this PR open to allow adding another commit later. Or just merge this and open a new topic, as the other stuff  is still related to feed but not to paths.

**Comment by acrylian** [comment]
Actually the table name is not really needed at all since it is only one table… Btw, this is not really about pages feeds although related ;-)

**Comment by bic-ed** [comment]
Well, is there for pages, was not there for news,. Beside that, I got an error in log from mysqli without this fix:
 `Column 'id' in where clause is ambiguous` 
And no feed cache generated either.

I know, I have to change the title of this PR.
I have a working fix for the dupe comments feed as well. I'll mail to you later...

**Comment by acrylian** [comment]
> Well, is there for pages, was not there for news,. Beside that, I got an error in log from mysqli without this fix:
Column 'id' in where clause is ambiguous

Yes, I know, because it was mixed within the same query. With one table the name is not needed with the column at all.  Well ;-)

**Comment by bic-ed** [comment]
Ok but then why the error in log? Can you reproduce it? To see the error you should visit a all comments feed page when not logged in, provided you have some articles with comments in a protected category. Quite well hidden, I know.

**Comment by acrylian** [comment]
I think because the query mixed columns with and without the table name.

**Comment by bic-ed** [comment]
The query trowing that error has also the comments table in it though. It is this one:
https://github.com/zenphoto/zenphoto/blob/e7b94f2074fc477aaf61021845355debc80ce6b3/zp-core/zp-extensions/zenpage/zenpage-template-functions.php#L2188

**Comment by acrylian** [comment]
Ah, yes, okay, my mistake, that's of course two tables and they have alias names both.

**Comment by acrylian** [comment]
I added a path parameter to al getLink() methods that should help with the actual path issue. Please try.

**Comment by bic-ed** [comment]
I see, I'm a bit lost on how to use this very welcome new feature in this context though. In getitemPages(), where I fixed the protocol thing with this PR, it can be changed from
`$feeditem['link'] = PROTOCOL . '://' . $this->host . $obj->getLink();`
to
`$feeditem['link'] = $obj->getLink(FULLWEBPATH);`

Am I right?
Beside this, we should do the same by removing the PROTOCOL part all around the rss code and replacing it with the new getLink(FULLWEBPATH)?

PS
Did you get my email with the other proposed changes?

**Comment by acrylian** [comment]
> $feeditem['link'] = $obj->getLink(FULLWEBPATH);
> Am I right?
Yes, correct, that's the intended usage.

> Beside this, we should do the same by removing the PROTOCOL part all around the rss code and replacing it with the new getLink(FULLWEBPATH)?

Yes, I changed all so we have it consistently for all getLink() methods. Even if the parameter is not always the first.

**Comment by acrylian** [comment]
> Did you get my email with the other proposed changes?

Yes, sorry, thought I replied but forgot apparently…

**Comment by bic-ed** [comment]
> Yes, I changed all so we have it consistently for all getLink() methods. Even if the parameter is not always the first.

Should I make the changes to add them to this PR?

**Comment by bic-ed** [comment]
I've tried but I'm afraid it is not working. There is a problem with the rewrite_path part when adding the FULLWEBPATH parameter to the new getLink() method. It is returning a full web path but prefixed with the WEBPATH constant.

**Comment by acrylian** [comment]
Ah, my mistake. rewrite_path actually has a parameter for the webpath that should be used instead of passing it to the urls itself…

     function rewrite_path($rewrite, $plain, $webpath = NULL) {
	   if (is_null($webpath)) {
		if (class_exists('seo_locale')) {
			$webpath = seo_locale::localePath();
		} else {
			$webpath = WEBPATH;
		}
	    }
           (…)

This needs some more work as the seo_locale part also needs change because by default it uses the webpath as well…

**Comment by acrylian** [comment]
Fix is up now.

**Comment by bic-ed** [comment]
Yes, it was tricky to add the parameter.  Tomorrow I'll try again.

**Comment by bic-ed** [comment]
Do you think at this point we can remove the host property from the feed class?

**Comment by acrylian** [comment]
> Do you think at this point we can remove the host property from the feed class?
Actually the idea of the recent changes was to get rid of these "manually construted URLs".  If it is not needed anywhere else it should not be needed anymore.

**Comment by bic-ed** [comment]
I've fixed a typo directly on master branch and added the rewritten links to this PR. I also removed the host property as it is not used anymore.
I've tested all kind of feeds and they seem to work as expected with the rewritten links like before, I hope I did not miss something...

**Comment by acrylian** [comment]
Did you try with the seolocale plugin enabled as well?

**Comment by bic-ed** [comment]
> Did you try with the seolocale plugin enabled as well?

No, sorry. I have not setup sub-domains on my local server and on the live one I'm not allowed to use 2 characters sub-domains, the minimum is 3.

**Comment by acrylian** [comment]
The seolocale is actually not for subdomains (that's an option of the dynamic locale plugin), but for adding the language code before the normal URL, like yourdomian.com/en/normalurl/

**Comment by bic-ed** [comment]
> The seolocale is actually not for subdomains (that's an option of the dynamic locale plugin), but for adding the language code before the normal URL, like yourdomian.com/en/normalurl/

Ah, I missed that. I've tried now enabling the plugin and manually inserting the prefix before the query, but all I get is a redirection to the url without the prefix. Sorry, I never looked at that plugin actually.

Meanwhile I've found several unused variables and a missing global declaration which leads to set
`$_zp_gallery_page = 'rss.php'`
as if it were a local (unused) variable inside the executeRSS() function. You can see it at the very end of rss.php file, though I don't know why the $_zp_gallery_page needs to be set there.
Should I add here a commit with the removed unused variables and the added global declaration?

**Comment by acrylian** [comment]
> Ah, I missed that. I've tried now enabling the plugin and manually inserting the prefix before the query, but all I get is a redirection to the url without the prefix. Sorry, I never looked at that plugin actually.

**Comment by bic-ed** [comment]
I see, but I don't get the language changed either! Yes, it would be great to have the language prefix remaining in the url.

**Comment by acrylian** [comment]
Regaridng $_zp_gallery_page. Indeed that is missing a global definition here. Since RSS is sort of front end we set the page here so nothing is confused. Sometimes template functions (and in the past even more of theme) are used and trigger on the gallery pages. Even some classes inernally hook on template context sometimes (a thing I intend to remove in the long run as classes should be iindependent for any backend or front end context).

**Comment by acrylian** [comment]
> I see, but I don't get the language changed either! Yes, it would be great to have the language prefix remaining in the url.

You need to be in multilingual mode and have at least two languages active. And you need modrewrite of course ;-) Works for me

**Comment by bic-ed** [comment]
Ah, I should have only one plugin enabled, is that so?

**Comment by acrylian** [comment]
> does not work for me because on a Window server.

Is that your live server - I know no host that not uses Linux/Unix - or the local one?

> Ah, I should have only one plugin enabled, is that so?

No, but of course the seolocalce does not make sense together with the subdomain option of the dymamiclocale. The latter is what actually switches the language.

**Comment by acrylian** [comment]
>  The latter is what actually switches the language.
To be exact: The seoLocalce sets a cookie for the language the dynamiclocale then uses after redirection.

**Comment by bic-ed** [comment]
I'm testing locally on Windows and it is for sure a windows problem. With seo_locale enabled stops working also dynamic_locale
But we are totally off topic, I can't get it work but it doesn't matter at the moment.

**Comment by bic-ed** [comment]
So, I'm going to add a new commit with the removed unused variables and the added global definition..

**Pull request merged**
