### PR TITLE
Updated translation

### PR DESCRIPTION
**Pull request by RolandTi**
Updated translation from the last master update.

_Note_ : I've got somes errors in Poedit 3.4.2 when I sync the files, only with .js files. I've been looking into zp-core/zp-extensions/uploader_jQuery/js/demo.js line29 without seeing anything.

```
Mon 22 Jan 15:41:50 2024: zp-core/js/jqueryui/jquery-ui.min.js:6: warning: Empty msgid.  It is reserved by GNU gettext:
	gettext("") returns the header entry with
	meta information, not the empty string.
Mon 22 Jan 15:41:50 2024: zp-core/zp-extensions/uploader_jQuery/js/demo.js:29: warning: unterminated string

```

### CODE REVIEW

**Comment by acrylian** [comment]
Thanks. You can just ignore those js warnings. gettext does not work with js. If they really bother you you can adjust the suffixes in your cataloguge settings to include only .php files: 

Bildschirmfoto 2024-01-22 um 16 12 58
Bildschirmfoto 2024-01-22 um 16 13 05

**Comment by RolandTi** [comment]
Ok, thanks !

**Comment by fretzl** [comment]
This is how it look for me:

Scherm­afbeelding

**Comment by acrylian** [comment]
Right, of course you can exclude paths, too. Perhaps explicitly setting .php might be simpler since we only care for those files anyway. Have to admit I never set any of these and just ignored them. Time to change that I guess ;-)

**Comment by RolandTi** [comment]
So I followed your example and exluded files and folder, because filtering by type of files is a pro option :-)

**Pull request merged**
