### PR TITLE
Apache Expires added

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
It should be great to use these expire headers settings.

Have a nice day.

### CODE REVIEW

**Comment by acrylian** [comment]
Sorry for the lack of reply on this. We decided not to incorporate these (as you noticed…). First, the values set might not be the right for everyone and second, it might be better if people who know what they are doing (like you) set these if needed themselves. Maybe in the future we find a way to add something like this more dynamically.

**Comment by Simounet** [comment]
I get your point but I think default values (maybe lower than mine) could be a great asset than no values at all. It's your call.

**Comment by zorodimanche** [comment]
+1

**Comment by thany** [comment]
These values are actually pretty pessimistic. I would personally set them to expire after much longer.
However, it is then up to the system to generate new urls for files that do change.

**Pull request closed without merging**
