### PR TITLE
TinyMCE plugin options: enable browser spellcheck, menu and define field heights

### PR DESCRIPTION
**Pull request by kuz-z-zma**
Several options:
- enable browser spellcheck (with warning on privacy concerns with browsers spellchecks in general)
- option to disable TinyMCE right-click menu in favour of browser right-click menu (with note on how to use it in conjunction with TinyMCE one)
- option to specify editing field height

### CODE REVIEW

**Comment by acrylian** [comment]
You are hopefully aware that you can create custom configurations, too. At least you could resist to update TinyMCE itself - we know we're a few versions back - as that would break tinyZenpage.

**Comment by acrylian** [comment]
Judging by feedback no one ever missed these ;-) Please understand that we really like to limit options to the necessary as we already have very plenty of them. We might refuse things in the future and especially for 1.6.5 as soon as we are in beta status hopefully soon.

**Comment by kuz-z-zma** [comment]
Most people won't add a lot of text to description of their photos, but when you want more than a few words - you do feel the need for a spellcheck, especially for languages you're not a native speaker of.

Also, browser spellchecks became more prevalent in last years - it wouldn't have bothered me, say 6 years ago, but now I want the convenience of it for the long-form writing.

**Comment by acrylian** [comment]
yes, I agree regarding spellchecking. It was really bad in older browsers, just as hyphenation was.

**Pull request merged**
