### PR TITLE
Added some comments to zp_apply_filter()

### PR DESCRIPTION
**Pull request by kochs-online**
I had a difficult time to figure out what the code does and added some comments for future interested parties. Also added an `if` instruction for documentation purposes, too.

Please feel free to merge or reject.

### CODE REVIEW

**Comment by acrylian** [comment]
Documentation is always good ;-) I will pull this in.

**Comment by acrylian** [comment]
Sadly had to revert your pull request as it caused serious issues. Utility buttons and tabs were missing and content macros stopped working. (my Git client also listed a lot more file changes than the two actual ones…

bildschirmfoto 2019-02-22 um 16 54 13

In any case in the future please always make sure you are on the latest master and only one issue per pull request (we had filter and exif)

**Comment by kochs-online** [comment]
I'm really sorry the pull request caused you trouble! :disappointed:

I guess I don't know my way around GitHub good enough yet. Might it be my repository wasn't merged with the master close enough to the pull request? I had the expectation that in any case only those changes I made to my repository where part of the pull request.

I'll go and make sure my repository is up-to-date and add those changes again.

**Comment by acrylian** [comment]
No problem, noticed in time and we all butcher things in GitHub some time ;-) I don't see the files on GitHub itself. 

But I don't think these are the issue. I actually think the new if clause you added on the zp_apply_filter() caused filters to break. Better leave this as it is this time and just re-send and review the Exif addition (see my comment on the other PR.

**Pull request merged**
