### PR TITLE
Always redirect URLs to the trailing slash version

### PR DESCRIPTION
**Pull request by Simounet**
Hi,
A little trick to avoid duplicate content.

### CODE REVIEW

**Comment by acrylian** [comment]
If this is an issue we probably should solve this internally and not by htaccess. We also support nginx where htaccess does not apply.

**Comment by Simounet** [comment]
I think this way is far better for performances. Earlier the 301 is served, earlier the user can see the page he is looking for. In the case of a vhost configuration, we should put this inside, avoiding the .htaccess read access.
We can translate this to Nginx with this `rewrite ^(.*[^/])$ $1/ permanent;`.
Anyway, I get your point and your solution will work everywhere but I think that we don't have so many servers to think about and these special cases should be handled.

**Comment by acrylian** [comment]
True, nginx is rare and the only server I know is our own. All urls are rewritten internally and not directly by htaccess. Anyway, we will talk about this and other possible htaccess additions soon. We will let you know.

**Comment by trisweb** [comment]
Has this been tested with all URLs? Does it impact standard files at the photo level?

Agree about duplicate URLs however; we should consider a solution to this more carefully.

**Comment by acrylian** [comment]
As far as I tested so far it does not interfere with any url we have, neither front nor backend.

**Comment by Simounet** [comment]
I'm using it since few weeks now and I didn't notice any error.

**Comment by acrylian** [comment]
There are several urls that do not work with this currently: Search related urls like gallery and news archives and also tag urls. I need to get those working before we can consider including this.

**Pull request merged**
