### PR TITLE
Simplified Chinese translation updated for v1.5.9

### PR DESCRIPTION
**Pull request by henrysting**

### CODE REVIEW

**Comment by acrylian** [comment]
Thanks for this unexpected translation!

**Comment by acrylian** [comment]
A few notes though: The translation should be for 1.6 already - also internally in the file catalogue - and you should be using the master (1.6a currently)from GitHub for translating as that will be the next release. Especially since strings changed since 1.5.9 already and surely a few more will follow until we release.

**Comment by henrysting** [comment]
OK. I will do more local test, and update it for 1.6.

**Comment by acrylian** [comment]
Thanks, that would be great.

**Pull request merged**
