### PR TITLE
contact_form: autocomplete enabled

### PR DESCRIPTION
**Pull request by kuz-z-zma**
Added attributes for autocomplete values to corresponding contact form fields.

### CODE REVIEW

**Comment by acrylian** [comment]
I am sorry, I will not take this in. Autocomplete is not enabled by default because of possible privacy concerns. If it should be optional (one option for all as individual would be overkill). 

I understand that some uses may want to provide that. I can look into that option later as some of the changes recently have a long term plan in mind already. Alternatively you can always create a custom form via the `/plugins/contact_form/form.php` folder or a theme `/themes/yourtheme/contact_form/form.php`

The reordering of the attributes is IMHO unnecessary as it does not matter at all (I understand the feel to a general order but this is really not important…)

**Comment by kuz-z-zma** [comment]
Having this attribute _not listed_ doesn't do anything though.
By default all browsers will attempt to fill forms by relying on _name_ of the input field anyway (as for most browsers autocomplete feature is an opt-out). Autocomplete attribute listed only helps browser to _correctly_ use their stored data to fill forms, by suggesting relevant input and removing their guesswork. 

Reordering of attributes, of course, doesn't matter in the grand scheme of things, but increases code readability when working with someone else code, which we do.

**Comment by acrylian** [comment]
True, actually It is an omission that forms don't have an default `autocomplete="off"` generally (which is most important on password related forms only of course). I will add an option for autocomplete and move your suggested attributes to a generalized method/function to handle them if that is enabled (as they otherwise would override the form attribute).

(Sidenote: I personally prefer to never let browsers fill in anything at all, I haven't set anything specific though and they do it automatically.)

> Reordering of attributes, of course, doesn't matter in the grand scheme of things, but increases code readability when working with someone else code, which we do.

Yes, but such tiny things often may cause unnecessary extra work for us (see the short main conversation recently).

**Comment by acrylian** [comment]
Okay, I will pull it in for now as it is easier then to work on the mentioned later on.

**Comment by kuz-z-zma** [comment]
Personally, I actively _disable_ autocomplete in browsers, as I don't want them to store sensitive data in cache and instead rely on password manager doing form fills too if needed (as well as passwords), as at least they have this info under password protection.

Browsers actually often ignore autocomplete="off" on username/password input too, if site uses https connection!

>Yes, but such tiny things often may cause unnecessary extra work for us (see the short main conversation recently).

That's why I fixed it myself )
I work a lot with code by others, and this inconsistency is understandable, but does slow work down and especially throws you off when troubleshooting smth.

**Comment by acrylian** [comment]
> Browsers actually often ignore autocomplete="off" on username/password input too, if site uses https connection!

Yeah, sadly it is all not consistent…

> That's why I fixed it myself ) I work a lot with code by others, and this inconsistency is understandable, but does slow work down and especially throws you off when troubleshooting smth.

Tiny changes may cause extra work in terms of double work for us as we have to port everything to our other release stream which partly has already different code.

**Comment by acrylian** [comment]
These forms are not yet affected but we have a lot grown code stuff that needs cleanup and we won't do that in 1.x anymore.

**Pull request merged**
