### PR TITLE
Italian translation 1.4.12

### PR DESCRIPTION
**Pull request by bic-ed**

### CODE REVIEW

**Comment by acrylian** [comment]
Sorry, I have to reject this. You might want to check the changes. I don't see Italian translation files at all but changes to the Japanese translation and various other file changes. Possibly your fork was out of date or something.

**Comment by bic-ed** [comment]
Ops, something went wrong. I'm sorry, I've done the translation for me, then I opened github again, after one year, to share the translation, but of course I still don't understand how to make a pull request from the git client on my pc. I'll try to learn and make new pull request.

**Comment by acrylian** [comment]
No problem. The easiest is to clone the repository to your GitHub, make sure it is current and then add/modify your translation files. Then the pull request made should contain only those. There is already an (your) translation include. 

Just be sure not to change anything else or add themes or something. But the client should let you decide which files to commit (don't use the official GitHub client currently so I am not sure how it does that).

**Comment by bic-ed** [comment]
I'm going to try again, I hope it works this time. I'm using official GitHub client and I see only the italian po and mo files under "changes".

**Pull request closed without merging**
