### PR TITLE
Missing strtotime for news archive date

### PR DESCRIPTION
**Pull request by bic-ed**

### CODE REVIEW

**Comment by acrylian** [comment]
Not sure why this is necessary but I don't know what value `$archivedate` has here? getFormattedLocaleDate()) accepts both a datetime string and a timestamp.

**Comment by bic-ed** [comment]
This is the breadcrumb in news archive view, with and without this commit
Screenshot 2022-11-24 at 10-13-57 News - My Photo gallery
Screenshot 2022-11-24 at 10-13-39 News - My Photo gallery

**Comment by acrylian** [comment]
Hm, okay, that looks more like a bug as $archivedate then must have an value that somehow does not work.

**Comment by bic-ed** [comment]
Then it most be wrong the date saved in $_zp_post_date?
Is it the one defined here?
`$_zp_post_date = removeTrailingSlash(sanitize($request['date']));`

**Comment by acrylian** [comment]
Possibly, I don't know without checking it specifially. The global might be modified somewhere else, globals are a bit inconvenient in that regard… Will take a look and let you know.

**Comment by bic-ed** [comment]
Searching the code, the only other place where it is modified is in admin-news-articles.php
`$_zp_post_date = sanitize($_GET['date']);`

**Comment by acrylian** [comment]
It was a bug with the new getFormattedLocaleDate() not using the right value for locale aware dates.

**Pull request closed without merging**
